behaviors:
  HummingBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 250
      buffer_size: 5000
      learning_rate: 0.0002
      beta: 0.0001
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 2
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1
      curiosity:
            strength: 0.25
            gamma: 0.9
    keep_checkpoints: 10
    max_steps: 100000000
    checkpoint_interval: 1500000
    summary_freq: 40000
    time_horizon: 500

engine_settings:
  time_scale: 10

environment_parameters:
  in_range_time:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: HummingBird
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 1.4
        value: 0.5
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: HummingBird
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 1.85
        value: 1.5
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: HummingBird
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3.0
        value: 2.5
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: HummingBird
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3.7
        value: 4
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: HummingBird
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 6
        value: 7