behaviors:
  HummingBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 250
      buffer_size: 5000
      learning_rate: 0.00005
      beta: 0.0001
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 2
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1
      curiosity:
            strength: 0.25
            gamma: 0.9
    keep_checkpoints: 10
    max_steps: 100000000
    checkpoint_interval: 1500000
    summary_freq: 40000
    time_horizon: 500