behaviors:
  HummingBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 350
      buffer_size: 7000
      learning_rate: 0.000075
      beta: 0.0001
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 2
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1
      curiosity:
            strength: 0.25
            gamma: 0.9
    keep_checkpoints: 10
    max_steps: 100000000
    checkpoint_interval: 1500000
    summary_freq: 40000
    time_horizon: 700

environment_parameters:
  herd_count:
    curriculum:
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: HummingBird
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 3.2
        value: 30